version: "3"
services:
  apache:
    build:
      context: ./
      dockerfile: Dockerfile
    stdin_open: true # docker run -i
    tty: true # docker run -t
    volumes:
      - ./volums/web:/var/www/html/
    expose:
      - 81
    ports:
      - 81:80
  db:
    image: mariadb:10.8
    environment:
      - MYSQL_ROOT_PASSWORD=politecnic
      - MYSQL_USER=alumne
      - MYSQL_PASSWORD=politecnic
      - MYSQL_DATABASE=prova
    volumes:
      - db-storage:/var/lib/mysql:delegated
    expose:
      - 3307
    ports:
      - 3307:3306
  phpmyadmin:
    image: phpmyadmin
    environment:
      - PMA_HOST=db
      - UPLOAD_LIMIT=300M
    # restart: always
    ports:
      - 8084:80
    volumes:
      - /sessions
    depends_on:
      - db
volumes:
  db-storage:
